/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prog2.vista;
import java.awt.Font;
import java.io.File;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import prog2.adaptador.Adaptador;
import static prog2.vista.CentralUB.DEMANDA_MAX;
import static prog2.vista.CentralUB.DEMANDA_MIN;
import static prog2.vista.CentralUB.VAR_NORM_MEAN;
import static prog2.vista.CentralUB.VAR_NORM_SEED;
import static prog2.vista.CentralUB.VAR_NORM_STD;

/**
 *
 * @author Albert
 */
public class AppCentralUB extends javax.swing.JFrame {

    private Adaptador adaptador;
    private float demandaPotencia;
    private float copiaBarrasControl;
    private boolean copiaReactor;
    private ArrayList<String> copiaBombas;
    
    public final static float DEMANDA_MAX = 1600;
    public final static float DEMANDA_MIN = 200;
    public final static float VAR_NORM_MEAN = 1000;
    public final static float VAR_NORM_STD = 600;
    public final static long VAR_NORM_SEED = 123;
    
    
    /** Generador aleatori de la demanda de potència **/
    private VariableNormal variableNormal;
    /**
     * Creates new form AppCentralUB
     */
    public AppCentralUB() {
        variableNormal = new VariableNormal(VAR_NORM_MEAN, VAR_NORM_STD, VAR_NORM_SEED);
        demandaPotencia = generaDemandaPotencia();
        /* Crea un nou adaptador i inicialitza els components */
        try {
            this.adaptador = new Adaptador();
            initComponents();
        } catch (CentralUBException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        txtDia.setText("1");
        txtDia.setEditable(false);
        txtDemandaPotencia.setText(String.valueOf(demandaPotencia));
        txtDemandaPotencia.setEditable(false);
        txtGuanysAcumulats.setEditable(false);
        try {
            txtGuanysAcumulats.setText(String.valueOf(adaptador.getGuanysAcumulats()));
        } catch (CentralUBException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        labelCentralUB.setFont(new Font("Calibri", Font.BOLD, 45));
    }
    
        private float generaDemandaPotencia(){
        float valor = Math.round(variableNormal.seguentValor());
        if (valor > DEMANDA_MAX)
            return DEMANDA_MAX;
        else
            if (valor < DEMANDA_MIN)
                return DEMANDA_MIN;
            else
                return valor;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrmVisualitzarInformacioCentral = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        cmboxOpcionsVisualitzar = new javax.swing.JComboBox<>();
        btnVisualitzar = new javax.swing.JButton();
        FrmGuardarDades = new javax.swing.JDialog();
        btnGuardarFitxer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtGuardarFitxer = new javax.swing.JTextField();
        FrmGestioComponentsCentral = new javax.swing.JFrame();
        btnDesactivarBomba = new javax.swing.JButton();
        lblReactor2 = new javax.swing.JLabel();
        txtfieldReactorActivat = new javax.swing.JTextField();
        btnActivarReactor = new javax.swing.JButton();
        cmboxBombesRefrigerants = new javax.swing.JComboBox<>();
        btnDesactivarReactor = new javax.swing.JButton();
        lblBombesRefrigerants2 = new javax.swing.JLabel();
        sldBarresControl = new javax.swing.JSlider();
        lblForaDeServei2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listForaDeServei = new javax.swing.JList<>();
        txtIntroduirInsercioBarresControl = new javax.swing.JTextField();
        btnActivarBomba = new javax.swing.JButton();
        btnIntroduirInsercioBarresControl = new javax.swing.JButton();
        btnAplicarModificacions = new javax.swing.JButton();
        btnCancelarModificacions = new javax.swing.JButton();
        FrmCarregaDades = new javax.swing.JDialog();
        btnCarregarFitxer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCarregarFitxer = new javax.swing.JTextField();
        btnVisualitzarInformacioCentral = new javax.swing.JButton();
        btnFinalitzarDia = new javax.swing.JButton();
        btnGuardarDades = new javax.swing.JButton();
        btnCarregarDades = new javax.swing.JButton();
        labelCentralUB = new javax.swing.JLabel();
        btnGestioComponentsCentral = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        txtDia = new javax.swing.JTextField();
        txtDemandaPotencia = new javax.swing.JTextField();
        txtGuanysAcumulats = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFinalitzarDia = new javax.swing.JTextArea();

        FrmVisualitzarInformacioCentral.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                FrmVisualitzarInformacioCentralComponentHidden(evt);
            }
        });

        jLabel2.setText("Visualitzar Informació Central");

        txtInfo.setColumns(20);
        txtInfo.setRows(5);
        jScrollPane2.setViewportView(txtInfo);

        cmboxOpcionsVisualitzar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estat Central", "Bitàcola", "Incidències", " " }));
        cmboxOpcionsVisualitzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboxOpcionsVisualitzarActionPerformed(evt);
            }
        });

        btnVisualitzar.setText("Visualitzar");
        btnVisualitzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualitzarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrmVisualitzarInformacioCentralLayout = new javax.swing.GroupLayout(FrmVisualitzarInformacioCentral.getContentPane());
        FrmVisualitzarInformacioCentral.getContentPane().setLayout(FrmVisualitzarInformacioCentralLayout);
        FrmVisualitzarInformacioCentralLayout.setHorizontalGroup(
            FrmVisualitzarInformacioCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmVisualitzarInformacioCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrmVisualitzarInformacioCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrmVisualitzarInformacioCentralLayout.createSequentialGroup()
                        .addComponent(cmboxOpcionsVisualitzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrmVisualitzarInformacioCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnVisualitzar)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        FrmVisualitzarInformacioCentralLayout.setVerticalGroup(
            FrmVisualitzarInformacioCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmVisualitzarInformacioCentralLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addComponent(btnVisualitzar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrmVisualitzarInformacioCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrmVisualitzarInformacioCentralLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(FrmVisualitzarInformacioCentralLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cmboxOpcionsVisualitzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        FrmGuardarDades.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                FrmGuardarDadesComponentHidden(evt);
            }
        });

        btnGuardarFitxer.setText("Guardar Dades");
        btnGuardarFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFitxerActionPerformed(evt);
            }
        });

        jLabel5.setText("Escriu el nom del fitxer: ");

        javax.swing.GroupLayout FrmGuardarDadesLayout = new javax.swing.GroupLayout(FrmGuardarDades.getContentPane());
        FrmGuardarDades.getContentPane().setLayout(FrmGuardarDadesLayout);
        FrmGuardarDadesLayout.setHorizontalGroup(
            FrmGuardarDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmGuardarDadesLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(FrmGuardarDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(txtGuardarFitxer)
                    .addComponent(btnGuardarFitxer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        FrmGuardarDadesLayout.setVerticalGroup(
            FrmGuardarDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmGuardarDadesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGuardarFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarFitxer)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        FrmGestioComponentsCentral.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                FrmGestioComponentsCentralComponentHidden(evt);
            }
        });

        btnDesactivarBomba.setText("Desactivar");
        btnDesactivarBomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarBombaActionPerformed(evt);
            }
        });

        lblReactor2.setText("Reactor :");

        txtfieldReactorActivat.setEditable(false);
        txtfieldReactorActivat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldReactorActivatActionPerformed(evt);
            }
        });

        btnActivarReactor.setText("Activar");
        btnActivarReactor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarReactorActionPerformed(evt);
            }
        });

        cmboxBombesRefrigerants.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bomba1", "Bomba2", "Bomba3", "Bomba4", " " }));

        btnDesactivarReactor.setText("Desactivar");
        btnDesactivarReactor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarReactorActionPerformed(evt);
            }
        });

        lblBombesRefrigerants2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBombesRefrigerants2.setText("Bombes Refrigerants");

        sldBarresControl.setMajorTickSpacing(20);
        sldBarresControl.setMinorTickSpacing(5);
        sldBarresControl.setOrientation(javax.swing.JSlider.VERTICAL);
        sldBarresControl.setPaintLabels(true);
        sldBarresControl.setPaintTicks(true);
        sldBarresControl.setInverted(true);
        sldBarresControl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldBarresControlStateChanged(evt);
            }
        });

        lblForaDeServei2.setText("Fora de Servei");

        jLabel3.setText("Inserció Barres de control");

        jScrollPane5.setViewportView(listForaDeServei);

        txtIntroduirInsercioBarresControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntroduirInsercioBarresControlActionPerformed(evt);
            }
        });

        btnActivarBomba.setText("Activar");
        btnActivarBomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarBombaActionPerformed(evt);
            }
        });

        btnIntroduirInsercioBarresControl.setText("Introduir");
        btnIntroduirInsercioBarresControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroduirInsercioBarresControlActionPerformed(evt);
            }
        });

        btnAplicarModificacions.setText("Aplicar Modificacions");
        btnAplicarModificacions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarModificacionsActionPerformed(evt);
            }
        });

        btnCancelarModificacions.setText("Cancelar Modificacions");
        btnCancelarModificacions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarModificacionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrmGestioComponentsCentralLayout = new javax.swing.GroupLayout(FrmGestioComponentsCentral.getContentPane());
        FrmGestioComponentsCentral.getContentPane().setLayout(FrmGestioComponentsCentralLayout);
        FrmGestioComponentsCentralLayout.setHorizontalGroup(
            FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIntroduirInsercioBarresControl, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(sldBarresControl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIntroduirInsercioBarresControl)))
                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblReactor2)
                                .addGap(18, 18, 18)
                                .addComponent(txtfieldReactorActivat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                .addComponent(btnActivarReactor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDesactivarReactor)))
                        .addGap(56, 56, 56)
                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBombesRefrigerants2)
                            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblForaDeServei2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                        .addComponent(btnActivarBomba)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDesactivarBomba))
                                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(cmboxBombesRefrigerants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancelarModificacions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAplicarModificacions, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        FrmGestioComponentsCentralLayout.setVerticalGroup(
            FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIntroduirInsercioBarresControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIntroduirInsercioBarresControl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldBarresControl, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addGap(62, 62, 62))
                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblReactor2)
                            .addComponent(txtfieldReactorActivat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActivarReactor)
                            .addComponent(btnDesactivarReactor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAplicarModificacions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarModificacions)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrmGestioComponentsCentralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                .addComponent(lblForaDeServei2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                .addComponent(cmboxBombesRefrigerants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnActivarBomba)
                                    .addComponent(btnDesactivarBomba))))
                        .addContainerGap(119, Short.MAX_VALUE))
                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                        .addComponent(lblBombesRefrigerants2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btnCarregarFitxer.setText("Carregar Dades");
        btnCarregarFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarFitxerActionPerformed(evt);
            }
        });

        jLabel6.setText("Selecciona fitxer: ");

        javax.swing.GroupLayout FrmCarregaDadesLayout = new javax.swing.GroupLayout(FrmCarregaDades.getContentPane());
        FrmCarregaDades.getContentPane().setLayout(FrmCarregaDadesLayout);
        FrmCarregaDadesLayout.setHorizontalGroup(
            FrmCarregaDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmCarregaDadesLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(FrmCarregaDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(txtCarregarFitxer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCarregarFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        FrmCarregaDadesLayout.setVerticalGroup(
            FrmCarregaDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmCarregaDadesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrmCarregaDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarregarFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarregarFitxer))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVisualitzarInformacioCentral.setText("Visualitzar Informacio Central");
        btnVisualitzarInformacioCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualitzarInformacioCentralActionPerformed(evt);
            }
        });

        btnFinalitzarDia.setText("Finalitzar Dia");
        btnFinalitzarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalitzarDiaActionPerformed(evt);
            }
        });

        btnGuardarDades.setText("Guardar Dades");
        btnGuardarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDadesActionPerformed(evt);
            }
        });

        btnCarregarDades.setText("Carregar Dades");
        btnCarregarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarDadesActionPerformed(evt);
            }
        });

        labelCentralUB.setText("CENTRALUB");

        btnGestioComponentsCentral.setText("Gestio Components Central");
        btnGestioComponentsCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioComponentsCentralActionPerformed(evt);
            }
        });

        label1.setText("Dia: ");

        label2.setText("Demanda Potencia: ");

        label3.setText("Guanys acumulats: ");

        txtFinalitzarDia.setColumns(20);
        txtFinalitzarDia.setRows(5);
        jScrollPane1.setViewportView(txtFinalitzarDia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(labelCentralUB, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDemandaPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGuanysAcumulats, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardarDades)
                                .addGap(42, 42, 42)
                                .addComponent(btnCarregarDades))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnVisualitzarInformacioCentral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGestioComponentsCentral)
                        .addGap(18, 18, 18)
                        .addComponent(btnFinalitzarDia)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDemandaPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGuanysAcumulats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCentralUB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestioComponentsCentral)
                    .addComponent(btnVisualitzarInformacioCentral)
                    .addComponent(btnFinalitzarDia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregarDades)
                    .addComponent(btnGuardarDades))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void btnVisualitzarInformacioCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualitzarInformacioCentralActionPerformed
                
        // Amagar el JFrame actual (Menu)
        setVisible(false);
        
        /* Fer visible la nova finestra */
        FrmVisualitzarInformacioCentral.setVisible(true);
        FrmVisualitzarInformacioCentral.setSize(500, 500);
    }//GEN-LAST:event_btnVisualitzarInformacioCentralActionPerformed

    private void btnGuardarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDadesActionPerformed
     FrmGuardarDades.setVisible(true);
     FrmGuardarDades.setSize(300, 300);
    }//GEN-LAST:event_btnGuardarDadesActionPerformed

    private void btnCarregarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarDadesActionPerformed
        FrmCarregaDades.setVisible(true);
        FrmCarregaDades.setSize(500, 300);
    }//GEN-LAST:event_btnCarregarDadesActionPerformed

    private void btnFinalitzarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalitzarDiaActionPerformed
        txtFinalitzarDia.setText(adaptador.finalitzaDia(demandaPotencia));
        demandaPotencia = generaDemandaPotencia();
        try {
            txtDia.setText(String.valueOf(adaptador.getDia()));
        } catch (CentralUBException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        txtDemandaPotencia.setText(String.valueOf(demandaPotencia));
        try {
            txtGuanysAcumulats.setText(String.valueOf(adaptador.getGuanysAcumulats()));
        } catch (CentralUBException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnFinalitzarDiaActionPerformed

    private void FrmVisualitzarInformacioCentralComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_FrmVisualitzarInformacioCentralComponentHidden
        setVisible(true);
    }//GEN-LAST:event_FrmVisualitzarInformacioCentralComponentHidden

    private void btnGuardarFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFitxerActionPerformed
        try {
            adaptador.guardaDades(txtGuardarFitxer.getText());
        } catch (CentralUBException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        FrmGuardarDades.setVisible(false);
    }//GEN-LAST:event_btnGuardarFitxerActionPerformed

    private void txtfieldReactorActivatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldReactorActivatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldReactorActivatActionPerformed

    private void btnActivarReactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarReactorActionPerformed
        // TODO add your handling code here:
        try {
             /* Desactivar el reactor */
            adaptador.activarReactor();
        } catch (CentralUBException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
            /* Mostrar Activat en el lablel*/
            txtfieldReactorActivat.setText("Activat");
    }//GEN-LAST:event_btnActivarReactorActionPerformed

    private void btnDesactivarReactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarReactorActionPerformed
        // TODO add your handling code here:
        try {
             /* Desactivar el reactor */
            adaptador.desactivarReactor();
        } catch (CentralUBException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
            /* Mostrar Activat en el lablel*/
            txtfieldReactorActivat.setText("Desactivat");
    }//GEN-LAST:event_btnDesactivarReactorActionPerformed

    private void sldBarresControlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldBarresControlStateChanged
       txtIntroduirInsercioBarresControl.setText(Float.toString(sldBarresControl.getValue()));
    }//GEN-LAST:event_sldBarresControlStateChanged

    private void txtIntroduirInsercioBarresControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntroduirInsercioBarresControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntroduirInsercioBarresControlActionPerformed

    private void btnGestioComponentsCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioComponentsCentralActionPerformed
        try {
            setVisible(false);
            FrmGestioComponentsCentral.setVisible(true);
            FrmGestioComponentsCentral.setSize(800, 600);
            omplirLlista();
            copiaBarrasControl = adaptador.getBarres();
            copiaReactor = adaptador.isReactorActivat();

        } catch (CentralUBException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnGestioComponentsCentralActionPerformed

    private void btnIntroduirInsercioBarresControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroduirInsercioBarresControlActionPerformed
        int valor = Integer.valueOf(txtIntroduirInsercioBarresControl.getText());
        sldBarresControl.setValue(valor);
    }//GEN-LAST:event_btnIntroduirInsercioBarresControlActionPerformed

    private void btnCancelarModificacionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarModificacionsActionPerformed
       try{
        adaptador.getBarres();
        if(copiaReactor){
            adaptador.activarReactor();
        }else{
            adaptador.desactivarReactor();
        }
       }catch(CentralUBException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());

       }
        
        setVisible(true);
        FrmGestioComponentsCentral.setVisible(false);
    }//GEN-LAST:event_btnCancelarModificacionsActionPerformed

    private void cmboxOpcionsVisualitzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboxOpcionsVisualitzarActionPerformed
       
    }//GEN-LAST:event_cmboxOpcionsVisualitzarActionPerformed

    private void btnVisualitzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualitzarActionPerformed
               int num = cmboxOpcionsVisualitzar.getSelectedIndex();
                
                switch(num){
                
                case 0:
            {
                try {
                    txtInfo.setText(adaptador.mostrarEstatCentral(demandaPotencia));
                } catch (CentralUBException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
                    break;

                
                case 1:
            {
                try {
                    txtInfo.setText(adaptador.mostrarBitacola());
                } catch (CentralUBException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
                    break;

                
                case 2:
            {
                try {
                    txtInfo.setText(adaptador.mostrarIncidencias());
                } catch (CentralUBException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
                    break;

                }
    }//GEN-LAST:event_btnVisualitzarActionPerformed

    private void btnCarregarFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarFitxerActionPerformed
                File fitxer;
        JFileChooser seleccio = new JFileChooser();

        int resultat = seleccio.showOpenDialog(this);
        if (resultat == JFileChooser.APPROVE_OPTION) {
           fitxer=seleccio.getSelectedFile();
           txtCarregarFitxer.setText(fitxer.toString());
    }
    }//GEN-LAST:event_btnCarregarFitxerActionPerformed

    private void btnActivarBombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarBombaActionPerformed
        try {
            adaptador.activarBomba(cmboxBombesRefrigerants.getSelectedIndex());
        } catch (CentralUBException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnActivarBombaActionPerformed

    private void btnDesactivarBombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarBombaActionPerformed
        try {
            adaptador.desactivarBomba(cmboxBombesRefrigerants.getSelectedIndex());
        } catch (CentralUBException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            
        }
    }//GEN-LAST:event_btnDesactivarBombaActionPerformed

    private void btnAplicarModificacionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarModificacionsActionPerformed

        setVisible(true);
        FrmGestioComponentsCentral.setVisible(false);
    }//GEN-LAST:event_btnAplicarModificacionsActionPerformed

    private void FrmGuardarDadesComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_FrmGuardarDadesComponentHidden
        setVisible(true);

    }//GEN-LAST:event_FrmGuardarDadesComponentHidden

    private void FrmGestioComponentsCentralComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_FrmGestioComponentsCentralComponentHidden
        setVisible(true);
    }//GEN-LAST:event_FrmGestioComponentsCentralComponentHidden
        
    void omplirLlista(){
        DefaultListModel model = new DefaultListModel();
        try {
            for(String item: adaptador.getBombesIncidencies()){
                model.addElement(item);
            }
        } catch (CentralUBException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        listForaDeServei.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppCentralUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppCentralUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppCentralUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppCentralUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppCentralUB().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog FrmCarregaDades;
    private javax.swing.JFrame FrmGestioComponentsCentral;
    private javax.swing.JDialog FrmGuardarDades;
    private javax.swing.JDialog FrmVisualitzarInformacioCentral;
    private javax.swing.JButton btnActivarBomba;
    private javax.swing.JButton btnActivarReactor;
    private javax.swing.JButton btnAplicarModificacions;
    private javax.swing.JButton btnCancelarModificacions;
    private javax.swing.JButton btnCarregarDades;
    private javax.swing.JButton btnCarregarFitxer;
    private javax.swing.JButton btnDesactivarBomba;
    private javax.swing.JButton btnDesactivarReactor;
    private javax.swing.JButton btnFinalitzarDia;
    private javax.swing.JButton btnGestioComponentsCentral;
    private javax.swing.JButton btnGuardarDades;
    private javax.swing.JButton btnGuardarFitxer;
    private javax.swing.JButton btnIntroduirInsercioBarresControl;
    private javax.swing.JButton btnVisualitzar;
    private javax.swing.JButton btnVisualitzarInformacioCentral;
    private javax.swing.JComboBox<String> cmboxBombesRefrigerants;
    private javax.swing.JComboBox<String> cmboxOpcionsVisualitzar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JLabel labelCentralUB;
    private javax.swing.JLabel lblBombesRefrigerants2;
    private javax.swing.JLabel lblForaDeServei2;
    private javax.swing.JLabel lblReactor2;
    private javax.swing.JList<String> listForaDeServei;
    private javax.swing.JSlider sldBarresControl;
    private javax.swing.JTextField txtCarregarFitxer;
    private javax.swing.JTextField txtDemandaPotencia;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextArea txtFinalitzarDia;
    private javax.swing.JTextField txtGuanysAcumulats;
    private javax.swing.JTextField txtGuardarFitxer;
    private javax.swing.JTextArea txtInfo;
    private javax.swing.JTextField txtIntroduirInsercioBarresControl;
    private javax.swing.JTextField txtfieldReactorActivat;
    // End of variables declaration//GEN-END:variables
}
