/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prog2.vista;
import java.io.File;
import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import prog2.adaptador.Adaptador;

/**
 *
 * @author Albert
 */
public class AppCentralUB extends javax.swing.JFrame {

    private Adaptador adaptador;
    private float demandaPotencia;
    /**
     * Creates new form AppCentralUB
     */
    public AppCentralUB() {
        /* Crea un nou adaptador i inicialitza els components */
        try {
            this.adaptador = new Adaptador();
            initComponents();
        } catch (CentralUBException ex) {
            System.out.println(ex.getMessage());
        }
        txtDia.setText("1");
        txtDemandaPotencia.setText(String.valueOf(demandaPotencia));
        try {
            txtGuanysAcumulats.setText(String.valueOf(adaptador.getGuanysAcumulats()));
        } catch (CentralUBException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrmVisualitzarInformacioCentral = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        cmboxOpcionsVisualitzar = new javax.swing.JComboBox<>();
        btnVisualitzar = new javax.swing.JButton();
        FrmGuardarDades = new javax.swing.JDialog();
        btnGuardarFitxer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtGuardarFitxer = new javax.swing.JTextField();
        FrmGestioComponentsCentral = new javax.swing.JFrame();
        btnDesactivarBomba2 = new javax.swing.JButton();
        lblReactor2 = new javax.swing.JLabel();
        txtfieldReactorActivat2 = new javax.swing.JTextField();
        btnActivarReactor2 = new javax.swing.JButton();
        cmboboxBombesRefgrigerants2 = new javax.swing.JComboBox<>();
        btnDesactivarReactor2 = new javax.swing.JButton();
        lblBombesRefrigerants2 = new javax.swing.JLabel();
        sldBarresControl = new javax.swing.JSlider();
        lblForaDeServei2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listForaDeServei2 = new javax.swing.JList<>();
        txtIntroduirInsercioBarresControl = new javax.swing.JTextField();
        lblEnServei2 = new javax.swing.JLabel();
        btnActivarBomba2 = new javax.swing.JButton();
        btnIntroduirInsercioBarresControl = new javax.swing.JButton();
        btnAplicarModificacions = new javax.swing.JButton();
        btnCancelarModificacions = new javax.swing.JButton();
        FrmCarregaDades = new javax.swing.JDialog();
        btnCarregarFitxer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCarregarFitxer = new javax.swing.JTextField();
        btnVisualitzarInformacioCentral = new javax.swing.JButton();
        btnFinalitzarDia = new javax.swing.JButton();
        btnGuardarDades = new javax.swing.JButton();
        btnCarregarDades = new javax.swing.JButton();
        CENTRALUB = new javax.swing.JLabel();
        btnGestioComponentsCentral = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        txtDia = new javax.swing.JTextField();
        txtDemandaPotencia = new javax.swing.JTextField();
        txtGuanysAcumulats = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFinalitzarDia = new javax.swing.JTextArea();

        FrmVisualitzarInformacioCentral.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                FrmVisualitzarInformacioCentralComponentHidden(evt);
            }
        });

        jLabel2.setText("Visualitzar Informació Central");

        txtInfo.setColumns(20);
        txtInfo.setRows(5);
        jScrollPane2.setViewportView(txtInfo);

        cmboxOpcionsVisualitzar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estat Central", "Bitàcola", "Incidències", " " }));
        cmboxOpcionsVisualitzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboxOpcionsVisualitzarActionPerformed(evt);
            }
        });

        btnVisualitzar.setText("Visualitzar");
        btnVisualitzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualitzarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrmVisualitzarInformacioCentralLayout = new javax.swing.GroupLayout(FrmVisualitzarInformacioCentral.getContentPane());
        FrmVisualitzarInformacioCentral.getContentPane().setLayout(FrmVisualitzarInformacioCentralLayout);
        FrmVisualitzarInformacioCentralLayout.setHorizontalGroup(
            FrmVisualitzarInformacioCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmVisualitzarInformacioCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrmVisualitzarInformacioCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrmVisualitzarInformacioCentralLayout.createSequentialGroup()
                        .addComponent(cmboxOpcionsVisualitzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrmVisualitzarInformacioCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnVisualitzar)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        FrmVisualitzarInformacioCentralLayout.setVerticalGroup(
            FrmVisualitzarInformacioCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmVisualitzarInformacioCentralLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addComponent(btnVisualitzar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrmVisualitzarInformacioCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrmVisualitzarInformacioCentralLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(FrmVisualitzarInformacioCentralLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cmboxOpcionsVisualitzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btnGuardarFitxer.setText("Guardar Dades");
        btnGuardarFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFitxerActionPerformed(evt);
            }
        });

        jLabel5.setText("Escriu el nom del fitxer: ");

        javax.swing.GroupLayout FrmGuardarDadesLayout = new javax.swing.GroupLayout(FrmGuardarDades.getContentPane());
        FrmGuardarDades.getContentPane().setLayout(FrmGuardarDadesLayout);
        FrmGuardarDadesLayout.setHorizontalGroup(
            FrmGuardarDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmGuardarDadesLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(FrmGuardarDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(txtGuardarFitxer)
                    .addComponent(btnGuardarFitxer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        FrmGuardarDadesLayout.setVerticalGroup(
            FrmGuardarDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmGuardarDadesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGuardarFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarFitxer)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        btnDesactivarBomba2.setText("Desactivar");

        lblReactor2.setText("Reactor :");

        txtfieldReactorActivat2.setEditable(false);
        txtfieldReactorActivat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldReactorActivat2ActionPerformed(evt);
            }
        });

        btnActivarReactor2.setText("Activar");
        btnActivarReactor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarReactor2ActionPerformed(evt);
            }
        });

        cmboboxBombesRefgrigerants2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDesactivarReactor2.setText("Desactivar");
        btnDesactivarReactor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarReactor2ActionPerformed(evt);
            }
        });

        lblBombesRefrigerants2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBombesRefrigerants2.setText("Bombes Refrigerants");

        sldBarresControl.setMajorTickSpacing(20);
        sldBarresControl.setMinorTickSpacing(5);
        sldBarresControl.setOrientation(javax.swing.JSlider.VERTICAL);
        sldBarresControl.setPaintLabels(true);
        sldBarresControl.setPaintTicks(true);
        sldBarresControl.setInverted(true);
        sldBarresControl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldBarresControlStateChanged(evt);
            }
        });

        lblForaDeServei2.setText("Fora de Servei");

        jLabel3.setText("Inserció Barres de control");

        listForaDeServei2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listForaDeServei2);

        txtIntroduirInsercioBarresControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntroduirInsercioBarresControlActionPerformed(evt);
            }
        });

        lblEnServei2.setText("En Servei");

        btnActivarBomba2.setText("Activar");

        btnIntroduirInsercioBarresControl.setText("Introduir");
        btnIntroduirInsercioBarresControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroduirInsercioBarresControlActionPerformed(evt);
            }
        });

        btnAplicarModificacions.setText("Aplicar Modificacions");

        btnCancelarModificacions.setText("Cancelar Modificacions");
        btnCancelarModificacions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarModificacionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrmGestioComponentsCentralLayout = new javax.swing.GroupLayout(FrmGestioComponentsCentral.getContentPane());
        FrmGestioComponentsCentral.getContentPane().setLayout(FrmGestioComponentsCentralLayout);
        FrmGestioComponentsCentralLayout.setHorizontalGroup(
            FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrmGestioComponentsCentralLayout.createSequentialGroup()
                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIntroduirInsercioBarresControl, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(sldBarresControl, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnCancelarModificacions))
                            .addComponent(btnIntroduirInsercioBarresControl)
                            .addComponent(btnAplicarModificacions))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                .addComponent(btnActivarReactor2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                .addComponent(lblForaDeServei2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(75, 75, 75)))
                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                .addComponent(btnDesactivarReactor2)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrmGestioComponentsCentralLayout.createSequentialGroup()
                                .addComponent(lblEnServei2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))))
                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                .addComponent(lblBombesRefrigerants2)
                                .addGap(158, 158, 158))
                            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrmGestioComponentsCentralLayout.createSequentialGroup()
                                        .addComponent(lblReactor2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtfieldReactorActivat2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71))
                                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(btnActivarBomba2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnDesactivarBomba2))
                                            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                                                .addGap(91, 91, 91)
                                                .addComponent(cmboboxBombesRefgrigerants2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap())))))))
        );
        FrmGestioComponentsCentralLayout.setVerticalGroup(
            FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReactor2)
                    .addComponent(txtfieldReactorActivat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActivarReactor2)
                    .addComponent(btnDesactivarReactor2))
                .addGap(38, 38, 38)
                .addComponent(lblBombesRefrigerants2)
                .addGap(18, 18, 18)
                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnServei2)
                    .addComponent(lblForaDeServei2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                        .addComponent(cmboboxBombesRefgrigerants2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActivarBomba2)
                            .addComponent(btnDesactivarBomba2))))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrmGestioComponentsCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIntroduirInsercioBarresControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntroduirInsercioBarresControl))
                .addGroup(FrmGestioComponentsCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldBarresControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(FrmGestioComponentsCentralLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnAplicarModificacions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarModificacions)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btnCarregarFitxer.setText("Carregar Dades");
        btnCarregarFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarFitxerActionPerformed(evt);
            }
        });

        jLabel6.setText("Selecciona fitxer: ");

        javax.swing.GroupLayout FrmCarregaDadesLayout = new javax.swing.GroupLayout(FrmCarregaDades.getContentPane());
        FrmCarregaDades.getContentPane().setLayout(FrmCarregaDadesLayout);
        FrmCarregaDadesLayout.setHorizontalGroup(
            FrmCarregaDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmCarregaDadesLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(FrmCarregaDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(txtCarregarFitxer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCarregarFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        FrmCarregaDadesLayout.setVerticalGroup(
            FrmCarregaDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmCarregaDadesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrmCarregaDadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarregarFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarregarFitxer))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVisualitzarInformacioCentral.setText("Visualitzar Informacio Central");
        btnVisualitzarInformacioCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualitzarInformacioCentralActionPerformed(evt);
            }
        });

        btnFinalitzarDia.setText("Finalitzar Dia");
        btnFinalitzarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalitzarDiaActionPerformed(evt);
            }
        });

        btnGuardarDades.setText("Guardar Dades");
        btnGuardarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDadesActionPerformed(evt);
            }
        });

        btnCarregarDades.setText("Carregar Dades");
        btnCarregarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarDadesActionPerformed(evt);
            }
        });

        CENTRALUB.setText("CENTRALUB");
        CENTRALUB.setMaximumSize(new java.awt.Dimension(65, 16));

        btnGestioComponentsCentral.setText("Gestio Components Central");
        btnGestioComponentsCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioComponentsCentralActionPerformed(evt);
            }
        });

        label1.setText("Dia: ");

        label2.setText("Demanda Potencia: ");

        label3.setText("Guanys acumulats: ");

        txtFinalitzarDia.setColumns(20);
        txtFinalitzarDia.setRows(5);
        jScrollPane1.setViewportView(txtFinalitzarDia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnVisualitzarInformacioCentral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGestioComponentsCentral)
                        .addGap(18, 18, 18)
                        .addComponent(btnFinalitzarDia)
                        .addContainerGap(351, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CENTRALUB, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(btnGuardarDades)
                                .addGap(42, 42, 42)
                                .addComponent(btnCarregarDades)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDemandaPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGuanysAcumulats, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CENTRALUB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDemandaPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGuanysAcumulats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGestioComponentsCentral)
                            .addComponent(btnVisualitzarInformacioCentral)
                            .addComponent(btnFinalitzarDia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCarregarDades)
                            .addComponent(btnGuardarDades)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void btnVisualitzarInformacioCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualitzarInformacioCentralActionPerformed
                
        // Amagar el JFrame actual (Menu)
        setVisible(false);
        
        /* Fer visible la nova finestra */
        FrmVisualitzarInformacioCentral.setVisible(true);
        FrmVisualitzarInformacioCentral.setSize(500, 500);
        
        if(!FrmVisualitzarInformacioCentral.isVisible()){
           this.setVisible(true);
        }
    }//GEN-LAST:event_btnVisualitzarInformacioCentralActionPerformed

    private void btnGuardarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDadesActionPerformed
     FrmGuardarDades.setVisible(true);
     FrmGuardarDades.setSize(100, 100);
    }//GEN-LAST:event_btnGuardarDadesActionPerformed

    private void btnCarregarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarDadesActionPerformed
        FrmCarregaDades.setVisible(true);
        FrmCarregaDades.setSize(500, 300);
    }//GEN-LAST:event_btnCarregarDadesActionPerformed

    private void btnFinalitzarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalitzarDiaActionPerformed
        txtFinalitzarDia.setText(adaptador.finalitzaDia(demandaPotencia));
        try {
            txtDia.setText(String.valueOf(adaptador.getDia()));
        } catch (CentralUBException ex) {
            System.out.println(ex.getMessage());
        }
        txtDemandaPotencia.setText(String.valueOf(demandaPotencia));
        try {
            txtGuanysAcumulats.setText(String.valueOf(adaptador.getGuanysAcumulats()));
        } catch (CentralUBException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnFinalitzarDiaActionPerformed

    private void FrmVisualitzarInformacioCentralComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_FrmVisualitzarInformacioCentralComponentHidden
        setVisible(true);
    }//GEN-LAST:event_FrmVisualitzarInformacioCentralComponentHidden

    private void btnGuardarFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFitxerActionPerformed
        try {
            adaptador.guardaDades(txtGuardarFitxer.getText());
        } catch (CentralUBException ex) {
            System.out.println(ex.getMessage());
        }
        FrmGuardarDades.setVisible(false);
    }//GEN-LAST:event_btnGuardarFitxerActionPerformed

    private void txtfieldReactorActivat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldReactorActivat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldReactorActivat2ActionPerformed

    private void btnActivarReactor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarReactor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActivarReactor2ActionPerformed

    private void btnDesactivarReactor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarReactor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDesactivarReactor2ActionPerformed

    private void sldBarresControlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldBarresControlStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_sldBarresControlStateChanged

    private void txtIntroduirInsercioBarresControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntroduirInsercioBarresControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntroduirInsercioBarresControlActionPerformed

    private void btnGestioComponentsCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioComponentsCentralActionPerformed
        setVisible(false);
        FrmGestioComponentsCentral.setVisible(true);
        FrmGestioComponentsCentral.setSize(500, 500);
    }//GEN-LAST:event_btnGestioComponentsCentralActionPerformed

    private void btnIntroduirInsercioBarresControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroduirInsercioBarresControlActionPerformed
        int valor = Integer.valueOf(txtIntroduirInsercioBarresControl.getText());
        sldBarresControl.setValue(valor);
    }//GEN-LAST:event_btnIntroduirInsercioBarresControlActionPerformed

    private void btnCancelarModificacionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarModificacionsActionPerformed
        setVisible(true);
        FrmGestioComponentsCentral.setVisible(false);
    }//GEN-LAST:event_btnCancelarModificacionsActionPerformed

    private void cmboxOpcionsVisualitzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboxOpcionsVisualitzarActionPerformed
       
    }//GEN-LAST:event_cmboxOpcionsVisualitzarActionPerformed

    private void btnVisualitzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualitzarActionPerformed
               int num = cmboxOpcionsVisualitzar.getSelectedIndex();
                
                switch(num){
                
                case 0:
            {
                try {
                    txtInfo.setText(adaptador.mostrarEstatCentral(demandaPotencia));
                } catch (CentralUBException ex) {
                    System.out.println(ex.getMessage());
                }
            }
                    break;

                
                case 1:
            {
                try {
                    txtInfo.setText(adaptador.mostrarBitacola());
                } catch (CentralUBException ex) {
                    System.out.println(ex.getMessage());
                }
            }
                    break;

                
                case 2:
            {
                try {
                    txtInfo.setText(adaptador.mostrarIncidencias());
                } catch (CentralUBException ex) {
                    System.out.println(ex.getMessage());
                }
            }
                    break;

                }
    }//GEN-LAST:event_btnVisualitzarActionPerformed

    private void btnCarregarFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarFitxerActionPerformed
                File fitxer;
        JFileChooser seleccio = new JFileChooser();

        int resultat = seleccio.showOpenDialog(this);
        if (resultat == JFileChooser.APPROVE_OPTION) {
           fitxer=seleccio.getSelectedFile();
           txtCarregarFitxer.setText(fitxer.toString());
    }
    }//GEN-LAST:event_btnCarregarFitxerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppCentralUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppCentralUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppCentralUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppCentralUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppCentralUB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CENTRALUB;
    private javax.swing.JDialog FrmCarregaDades;
    private javax.swing.JFrame FrmGestioComponentsCentral;
    private javax.swing.JDialog FrmGuardarDades;
    private javax.swing.JDialog FrmVisualitzarInformacioCentral;
    private javax.swing.JButton btnActivarBomba2;
    private javax.swing.JButton btnActivarReactor2;
    private javax.swing.JButton btnAplicarModificacions;
    private javax.swing.JButton btnCancelarModificacions;
    private javax.swing.JButton btnCarregarDades;
    private javax.swing.JButton btnCarregarFitxer;
    private javax.swing.JButton btnDesactivarBomba2;
    private javax.swing.JButton btnDesactivarReactor2;
    private javax.swing.JButton btnFinalitzarDia;
    private javax.swing.JButton btnGestioComponentsCentral;
    private javax.swing.JButton btnGuardarDades;
    private javax.swing.JButton btnGuardarFitxer;
    private javax.swing.JButton btnIntroduirInsercioBarresControl;
    private javax.swing.JButton btnVisualitzar;
    private javax.swing.JButton btnVisualitzarInformacioCentral;
    private javax.swing.JComboBox<String> cmboboxBombesRefgrigerants2;
    private javax.swing.JComboBox<String> cmboxOpcionsVisualitzar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JLabel lblBombesRefrigerants2;
    private javax.swing.JLabel lblEnServei2;
    private javax.swing.JLabel lblForaDeServei2;
    private javax.swing.JLabel lblReactor2;
    private javax.swing.JList<String> listForaDeServei2;
    private javax.swing.JSlider sldBarresControl;
    private javax.swing.JTextField txtCarregarFitxer;
    private javax.swing.JTextField txtDemandaPotencia;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextArea txtFinalitzarDia;
    private javax.swing.JTextField txtGuanysAcumulats;
    private javax.swing.JTextField txtGuardarFitxer;
    private javax.swing.JTextArea txtInfo;
    private javax.swing.JTextField txtIntroduirInsercioBarresControl;
    private javax.swing.JTextField txtfieldReactorActivat2;
    // End of variables declaration//GEN-END:variables
}
