/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prog2.vista;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import prog2.adaptador.Adaptador;

/**
 *
 * @author Albert
 */
public class FrameGestioComponents extends javax.swing.JFrame{
    /* Objecte adaptador */
    private static Adaptador adaptador;
    
    /* Objecte DefaultListModel per afegir fàcilment les bombes fora de servei a la JList*/
    private DefaultListModel<String> listModelForaDeServei;
    
    /**
     * Creates new form FrameGestioComponents
     * @param adaptador
     */
    public FrameGestioComponents(Adaptador adaptador) {
        this.adaptador = adaptador;
        listModelForaDeServei = new DefaultListModel<>();
        initComponents();
        listForaDeServei.setModel(listModelForaDeServei);  // Set the model to the JList
        populateForaDeServeiList();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jMenuItem1 = new javax.swing.JMenuItem();
        lblReactor = new javax.swing.JLabel();
        txtfieldReactorActivat = new javax.swing.JTextField();
        btnActivarReactor = new javax.swing.JButton();
        btnDesactivarReactor = new javax.swing.JButton();
        sliderInsercioBarres = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        txtInsercio = new javax.swing.JTextField();
        cmboboxBombesRefgrigerants = new javax.swing.JComboBox<>();
        lblBombesRefrigerants = new javax.swing.JLabel();
        lblForaDeServei = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listForaDeServei = new javax.swing.JList<>();
        lblEnServei = new javax.swing.JLabel();
        btnActivarBomba = new javax.swing.JButton();
        btnDesactivarBomba = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReactor.setText("Reactor :");

        txtfieldReactorActivat.setEditable(false);
        txtfieldReactorActivat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldReactorActivatActionPerformed(evt);
            }
        });

        btnActivarReactor.setText("Activar");
        btnActivarReactor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarReactorActionPerformed(evt);
            }
        });

        btnDesactivarReactor.setText("Desactivar");
        btnDesactivarReactor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarReactorActionPerformed(evt);
            }
        });

        sliderInsercioBarres.setMajorTickSpacing(20);
        sliderInsercioBarres.setMinorTickSpacing(5);
        sliderInsercioBarres.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderInsercioBarres.setPaintLabels(true);
        sliderInsercioBarres.setPaintTicks(true);
        sliderInsercioBarres.setInverted(true);
        sliderInsercioBarres.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderInsercioBarresStateChanged(evt);
            }
        });

        jLabel1.setText("Inserció Barres de control");

        txtInsercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsercioActionPerformed(evt);
            }
        });

        cmboboxBombesRefgrigerants.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblBombesRefrigerants.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBombesRefrigerants.setText("Bombes Refrigerants");

        lblForaDeServei.setText("Fora de Servei");

        listForaDeServei.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listForaDeServei);

        lblEnServei.setText("En Servei");

        btnActivarBomba.setText("Activar");

        btnDesactivarBomba.setText("Desactivar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtInsercio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(sliderInsercioBarres, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnActivarReactor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblForaDeServei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(75, 75, 75)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDesactivarReactor)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblEnServei, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblReactor)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtfieldReactorActivat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(btnActivarBomba)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnDesactivarBomba))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(91, 91, 91)
                                                .addComponent(cmboboxBombesRefgrigerants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap())))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBombesRefrigerants)
                                .addGap(158, 158, 158))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReactor)
                    .addComponent(txtfieldReactorActivat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActivarReactor)
                    .addComponent(btnDesactivarReactor))
                .addGap(38, 38, 38)
                .addComponent(lblBombesRefrigerants)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnServei)
                    .addComponent(lblForaDeServei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmboboxBombesRefgrigerants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActivarBomba)
                            .addComponent(btnDesactivarBomba))))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(txtInsercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderInsercioBarres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfieldReactorActivatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldReactorActivatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldReactorActivatActionPerformed

    
    
/*********      Activar i desactivar reactor    **********/
    
    private void btnActivarReactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarReactorActionPerformed
        // TODO add your handling code here:
        try {
             /* Activar el reactor */
            adaptador.activarReactor();
        } catch (CentralUBException ex) {
            System.out.println(ex.getMessage());
        }
            /* Mostrar Activat en el lablel*/
            txtfieldReactorActivat.setText("Activat");
    }//GEN-LAST:event_btnActivarReactorActionPerformed

    private void btnDesactivarReactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarReactorActionPerformed
        // TODO add your handling code here:
        try {
             /* Desactivar el reactor */
            adaptador.desactivarReactor();
        } catch (CentralUBException ex) {
            System.out.println(ex.getMessage());
        }
            /* Mostrar Activat en el lablel*/
            txtfieldReactorActivat.setText("Desactivat");
    }//GEN-LAST:event_btnDesactivarReactorActionPerformed

/**********     Modificar l'inserció de les barres de control   *********/
    
    
    private void sliderInsercioBarresStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderInsercioBarresStateChanged
        // TODO add your handling code here:
        
        /* Extreure el valor de l'inseció de les barres i mostrar-lo */
        txtInsercio.setText(Integer.toString(sliderInsercioBarres.getValue()) + "%");
    }//GEN-LAST:event_sliderInsercioBarresStateChanged

    private void txtInsercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsercioActionPerformed
        try {
            // TODO add your handling code here:
            
            /* Extreu el grau d'inserció del textfield quan aquest ha estat modificat */
            int val = Integer.parseInt(txtInsercio.getText());
            
            /* Estableix el valor del slider al del textfield */
            sliderInsercioBarres.setValue(val);
            
            /* Inserir les barres */
            adaptador.insertarBarres((float) val);
        } catch (CentralUBException ex) {
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_txtInsercioActionPerformed

    private void populateForaDeServeiList() {
//        try {
//            List<String> foraDeServeiItems;
//        for(int i = 0; i < 3; i++){
//            if(adaptador.)
//        }
//        
//
//        listModelForaDeServei.clear(); // Clear existing items
//        for (String item : foraDeServeiItems) {
//            listModelForaDeServei.addElement(item); // Add items to the list model
//        }
//    } catch (CentralUBException ex) {
//        JOptionPane.showMessageDialog(this, "Error fetching 'Fora de Servei' items: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGestioComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGestioComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGestioComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGestioComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGestioComponents(adaptador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivarBomba;
    private javax.swing.JButton btnActivarReactor;
    private javax.swing.JButton btnDesactivarBomba;
    private javax.swing.JButton btnDesactivarReactor;
    private javax.swing.JComboBox<String> cmboboxBombesRefgrigerants;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBombesRefrigerants;
    private javax.swing.JLabel lblEnServei;
    private javax.swing.JLabel lblForaDeServei;
    private javax.swing.JLabel lblReactor;
    private javax.swing.JList<String> listForaDeServei;
    private javax.swing.JSlider sliderInsercioBarres;
    private javax.swing.JTextField txtInsercio;
    private javax.swing.JTextField txtfieldReactorActivat;
    // End of variables declaration//GEN-END:variables

    
}
